from __future__ import annotations

from base import BaseModel
from base import BaseService
from aqi_agent.domain.planner.models import SubTaskModel
from aqi_agent.shared.models.state import ChatwithDBState
from aqi_agent.shared.settings import CriticAgentSettings
from fastapi.encoders import jsonable_encoder
from lite_llm import CompletionMessage
from lite_llm import LiteLLMInput
from lite_llm import LiteLLMService
from lite_llm import MessageRole
from logger import get_logger
from pydantic import Field

from .models import CriticAgentModel
from .prompts import CRITIC_SYSTEM_PROMPT
from .prompts import CRITIC_USER_PROMPT

logger = get_logger(__name__)


class CriticAgentInput(BaseModel):
    rephrased_question: str = Field(
        ...,
        description='The rephrased user question to critique.',
    )
    generated_sql: str = Field(
        ...,
        description='The SQL query generated by the SQL Generator.',
    )
    subtasks: list[SubTaskModel] = Field(
        default_factory=list,
        description='List of subtasks decomposed from the planner.',
    )
    planning_summary: str = Field(
        default='',
        description='Summary of the planning analysis.',
    )
    execution_error: str = Field(
        ...,
        description='Error message from the failed SQL execution to analyze.',
    )
    db_schema: str = Field(
        default='',
        description='Database schema information for context.',
    )
    
class CriticAgentOutput(BaseModel):
    """Output model for the Critic Agent Service."""

    error_explanation: str = Field(
        default='',
        description='A clear explanation of why the SQL execution error occurred.',
    )
    fixed_sql: str = Field(
        default='',
        description='A corrected SQL query that addresses the identified issues.',
    )
    is_fixed: bool = Field(
        default=False,
        description='Indicates whether the SQL query was successfully fixed.',
    )
    
    
class CriticAgentService(BaseService):
    """
    Critic Agent Service for Text-to-SQL systems.

    This service analyzes failed SQL queries and provides corrections by:
    1. Identifying the root cause of SQL execution errors.
    2. Generating corrected SQL queries based on the original planning context.

    The service uses the planning summary and subtasks to understand the original
    intent and produces syntactically and semantically correct SQL queries.

    Attributes:
        litellm_service: The LLM service for processing natural language requests.
        settings: Configuration settings for the Critic Agent.
    """

    litellm_service: LiteLLMService
    settings: CriticAgentSettings

    @staticmethod
    def _format_subtasks(subtasks: list[SubTaskModel]) -> str:
        """
        Format subtasks into a string representation for the prompt.

        Args:
            subtasks: List of subtask models to format.

        Returns:
            A formatted string representation of subtasks.
        """
        if not subtasks:
            return 'No subtasks available.'

        formatted_tasks = []
        for task in subtasks:
            task_str = (
                f'- Task ID: {task.task_id}\n'
                f'  Description: {task.description}\n'
                f'  Depends on: {", ".join(task.depends_on) if task.depends_on else "None"}\n'
                f'  SQL Hint: {task.sql_hint or "None"}'
            )
            formatted_tasks.append(task_str)

        return '\n'.join(formatted_tasks)

    async def process(self, inputs: CriticAgentInput) -> CriticAgentOutput:
        """
        Process a critic request to analyze and fix a failed SQL query.

        Takes a failed SQL query along with its execution error and planning context,
        then generates a corrected SQL query with an explanation of the error.

        Args:
            inputs: The input data containing the failed SQL query,
                   execution error, subtasks, and planning summary.

        Returns:
            A CriticAgentOutput containing the error explanation,
            fixed SQL query, and fix status.

        Raises:
            ValueError: If the input SQL query or execution error is invalid.
            Exception: If the LLM service fails to process the request.
        """
        try:
            # Format subtasks for the user prompt
            subtasks_str = self._format_subtasks(inputs.subtasks)

            # Build the user prompt
            user_prompt = CRITIC_USER_PROMPT.format(
                rephrased_question=inputs.rephrased_question,
                sql_query=inputs.generated_sql,
                execution_error=inputs.execution_error,
                planning_summary=inputs.planning_summary or 'No planning summary available.',
                subtasks=subtasks_str,
                db_schema=inputs.db_schema,
            )

            messages: list[CompletionMessage] = [
                CompletionMessage(
                    role=MessageRole.SYSTEM,
                    content=CRITIC_SYSTEM_PROMPT,
                ),
                CompletionMessage(
                    role=MessageRole.USER,
                    content=user_prompt,
                ),
            ]

            response = await self.litellm_service.process_async(
                inputs=LiteLLMInput(
                    message=messages,
                    return_type=CriticAgentModel,
                    frequency_penalty=self.settings.frequency_penalty,
                    n=self.settings.n,
                    model=self.settings.model,
                    presence_penalty=self.settings.presence_penalty,
                ),
            )

            critic_result: CriticAgentModel = CriticAgentModel(
                **jsonable_encoder(response.response),
            )

            logger.info(
                'Critic agent result',
                extra={
                    'is_fixed': critic_result.is_fixed,
                    'error_explanation': critic_result.error_explanation if critic_result.error_explanation else '',
                    'has_fixed_sql': bool(critic_result.fixed_sql),
                },
            )

            return CriticAgentOutput(
                error_explanation=critic_result.error_explanation,
                fixed_sql=critic_result.fixed_sql,
                is_fixed=bool(critic_result.fixed_sql),
            )
        except Exception as e:
            logger.warning(
                'Error processing critic agent request',
                extra={
                    'error': str(e),
                    'input_sql': inputs.generated_sql,
                    'execution_error': inputs.execution_error,
                },
            )
            return CriticAgentOutput(
                error_explanation=f'Failed to analyze SQL error: {e!s}',
                fixed_sql='',
                is_fixed=False,
            )

    async def gprocess(self, state: ChatwithDBState) -> dict:
        """
        Wrapper method for executing critic analysis within the LangGraph state graph.

        Extracts necessary information from the state (failed SQL, execution error,
        planning context) and returns the critic result as a dictionary compatible
        with the state graph.

        Args:
            state: The ChatwithDBState containing SQL query, execution error,
                   and planning context.

        Returns:
            dict: Dictionary containing 'critic_state' with the critic results
                  including error explanation, fixed SQL, and fix status.
                  Returns default values if processing fails.
        """
        try:
            # Extract rephrased question
            rephrased_state = state.get('rephrased_state', {})
            rephrased_question = rephrased_state.get(
                'rephrased_main_question',
                state.get('question', ''),
            )

            # Extract SQL execution state
            sql_execution_state = state.get('sql_execution_state', {})
            sql_generator_state = state.get('sql_generator_state', {})
            failed_sql = sql_generator_state.get('sql_query', '')
            execution_error = sql_execution_state.get('error_message', '')

            # Extract planner state for context
            planner_state = state.get('planner_state', {})
            planning_summary = planner_state.get('planning_summary', '')
            subtasks_data = planner_state.get('subtasks', [])

            # Extract schema context
            table_pruner_state = state.get('table_pruner_state', {})
            db_schema = table_pruner_state.get('pruned_schema', '')

            # Convert subtasks to SubTaskModel
            subtasks = [
                SubTaskModel(
                    task_id=t.get('task_id', ''),
                    description=t.get('description', ''),
                    depends_on=t.get('depends_on', []),
                    sql_hint=t.get('sql_hint', ''),
                )
                for t in subtasks_data
            ] if subtasks_data else []

            critic_result = await self.process(
                inputs=CriticAgentInput(
                    rephrased_question=rephrased_question,
                    generated_sql=failed_sql,
                    execution_error=execution_error if execution_error else 'No execution error message available.',
                    subtasks=subtasks,
                    planning_summary=planning_summary,
                    db_schema=db_schema,
                ),
            )

            return {
                'critic_agent_state': {
                    'error_explanation': critic_result.error_explanation,
                    'is_fixed': critic_result.is_fixed,
                },
                'sql_generator_state': {
                    'sql_query': critic_result.fixed_sql,
                },
            }
        except Exception as e:
            logger.warning(
                'Failed to process critic analysis in gprocess, using fallback values.',
                extra={
                    'error': str(e),
                    'original_sql': state.get('sql_generator_state', {}).get('sql_query'),
                },
            )
            return {
                'critic_agent_state': {
                    'error_explanation': f'Failed to analyze SQL error: {e!s}',
                    'fixed_sql': '',
                    'is_fixed': False,
                },
            }
