"""Populate Redis with frequent column values from PostgreSQL for FuzzyCorrector.

FuzzyCorrectorService reads Redis keys with pattern:
    frequent_values:<table_name>.<column_name>  →  LIST of string values

This script queries PostgreSQL for DISTINCT values of text columns used in
WHERE clauses (identified from the MDL schema) and pushes them into Redis
as LIST structures so that ``_find_cached_values_for_column()`` can look
them up via ``SCAN`` + ``LRANGE``.

Usage:
    python script/populate_redis_cache.py [--flush]     # --flush clears existing keys first
    python script/populate_redis_cache.py --dry-run     # preview without writing
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import psycopg2
import redis
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Load .env from project root (script/ → ../.env)
# ---------------------------------------------------------------------------
env_path = Path(__file__).resolve().parent.parent / '.env'
if env_path.exists():
    load_dotenv(env_path)
else:
    load_dotenv()


# ---------------------------------------------------------------------------
# Configuration: which columns to cache
# ---------------------------------------------------------------------------
# Each entry: (table_name, column_name, optional SQL override)
# The Redis key will be: frequent_values:<table>.<column>
#
# These are the TEXT columns that appear in WHERE clauses generated by the
# text2sql agent.  The MDL defines 4 tables (provinces, districts,
# air_component, distric_stats) and these are the filterable string columns.
COLUMNS_TO_CACHE: list[tuple[str, str, str | None]] = [
    # ── districts ──────────────────────────────────────────────
    ('districts', 'name', None),                 # "Phường Hoàn Kiếm", "Xã Ba Vì", …
    ('districts', 'normalized_name', None),       # "phuong_hoan_kiem", …
    ('districts', 'id', None),                    # "ID_00000", …
    ('districts', 'administrative_id', None),     # "VNM.27.1_1", …

    # ── provinces ──────────────────────────────────────────────
    ('provinces', 'name', None),                  # "Hà Nội"
    ('provinces', 'id', None),                    # "12"

    # ── air_component ─────────────────────────────────────────
    ('air_component', 'name', None),              # "aqi", "PM2.5", "PM10", …

    # ── distric_stats ─────────────────────────────────────────
    ('distric_stats', 'component_id', None),      # "aqi", "PM2.5"
    ('distric_stats', 'district_id', None),       # "ID_00008", …
]

# Redis key prefix – must match settings.yaml  autocorrector.redis_key_prefix
REDIS_KEY_PREFIX = os.getenv('AUTOCORRECTOR__REDIS_KEY_PREFIX', 'frequent_values')


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Populate Redis cache with frequent column values from PostgreSQL',
    )
    parser.add_argument(
        '--flush', action='store_true',
        help='Delete all existing frequent_values:* keys before populating',
    )
    parser.add_argument(
        '--dry-run', action='store_true',
        help='Print what would be written without actually touching Redis',
    )
    parser.add_argument(
        '--pg-host', default=os.getenv('POSTGRES__HOST', 'localhost'),
    )
    parser.add_argument(
        '--pg-port', type=int, default=int(os.getenv('POSTGRES__PORT', '15432')),
    )
    parser.add_argument(
        '--pg-db', default=os.getenv('POSTGRES__DB', 'hanoiair_db'),
    )
    parser.add_argument(
        '--pg-user', default=os.getenv('POSTGRES__USER', 'hanoiair_user'),
    )
    parser.add_argument(
        '--pg-pass', default=os.getenv('POSTGRES__PASSWORD', 'hanoiair_pass'),
    )
    parser.add_argument(
        '--redis-host', default=os.getenv('REDIS__HOST', 'localhost'),
    )
    parser.add_argument(
        '--redis-port', type=int, default=int(os.getenv('REDIS__PORT', '6379')),
    )
    parser.add_argument(
        '--redis-db', type=int, default=int(os.getenv('REDIS__DB', '0')),
    )
    parser.add_argument(
        '--redis-password', default=os.getenv('REDIS__PASSWORD', None),
    )
    return parser.parse_args()


def get_distinct_values(
    pg_conn,
    table: str,
    column: str,
    custom_sql: str | None = None,
) -> list[str]:
    """Query PostgreSQL for distinct non-null values of a text column."""
    cur = pg_conn.cursor()
    if custom_sql:
        cur.execute(custom_sql)
    else:
        # Use parameterised identifiers safely (table/column are from our config, not user input)
        cur.execute(
            f'SELECT DISTINCT "{column}" FROM "{table}" '
            f'WHERE "{column}" IS NOT NULL '
            f'ORDER BY "{column}"',
        )
    rows = cur.fetchall()
    cur.close()
    return [str(row[0]) for row in rows]


def populate(args: argparse.Namespace) -> None:
    # ── Connect PostgreSQL ────────────────────────────────────────────────
    pg_conn = psycopg2.connect(
        host=args.pg_host,
        port=args.pg_port,
        dbname=args.pg_db,
        user=args.pg_user,
        password=args.pg_pass,
    )
    print(f'✅ Connected to PostgreSQL {args.pg_host}:{args.pg_port}/{args.pg_db}')

    # ── Connect Redis ─────────────────────────────────────────────────────
    r = redis.Redis(
        host=args.redis_host,
        port=args.redis_port,
        db=args.redis_db,
        password=args.redis_password,
        decode_responses=True,
    )
    r.ping()
    print(f'✅ Connected to Redis {args.redis_host}:{args.redis_port}/{args.redis_db}')

    # ── Optionally flush old keys ─────────────────────────────────────────
    if args.flush and not args.dry_run:
        pattern = f'{REDIS_KEY_PREFIX}:*'
        deleted = 0
        for key in r.scan_iter(match=pattern, count=500):
            r.delete(key)
            deleted += 1
        print(f'🗑️  Flushed {deleted} existing keys matching "{pattern}"')

    # ── Populate ──────────────────────────────────────────────────────────
    total_keys = 0
    total_values = 0

    for table, column, custom_sql in COLUMNS_TO_CACHE:
        redis_key = f'{REDIS_KEY_PREFIX}:{table}.{column}'
        values = get_distinct_values(pg_conn, table, column, custom_sql)

        if not values:
            print(f'  ⚠️  {redis_key}: no values found in PG — skipped')
            continue

        if args.dry_run:
            print(f'  [DRY-RUN] {redis_key}: {len(values)} values')
            for v in values[:5]:
                print(f'            → {v}')
            if len(values) > 5:
                print(f'            … and {len(values) - 5} more')
        else:
            # Delete existing key to avoid duplicates, then push all values
            r.delete(redis_key)
            r.rpush(redis_key, *values)
            print(f'  ✅ {redis_key}: {len(values)} values pushed')

        total_keys += 1
        total_values += len(values)

    pg_conn.close()

    print()
    print(f'📊 Summary: {total_keys} keys, {total_values} total values')
    if args.dry_run:
        print('   (dry-run mode — nothing was written to Redis)')


def main() -> None:
    args = parse_args()
    try:
        populate(args)
    except Exception as e:
        print(f'❌ Error: {e}', file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
